// flow-typed signature: a9e60cc8d83827aa940288af354e72df
// flow-typed version: <<STUB>>/postcss-px2rem_v^0.3.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-px2rem'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-px2rem' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-px2rem/lib/index' {
  declare module.exports: any;
}

declare module 'postcss-px2rem/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-px2rem/index' {
  declare module.exports: $Exports<'postcss-px2rem'>;
}
declare module 'postcss-px2rem/index.js' {
  declare module.exports: $Exports<'postcss-px2rem'>;
}
declare module 'postcss-px2rem/lib/index.js' {
  declare module.exports: $Exports<'postcss-px2rem/lib/index'>;
}
declare module 'postcss-px2rem/test/test.js' {
  declare module.exports: $Exports<'postcss-px2rem/test/test'>;
}
